import { Playfair_Display, Montserrat } from "next/font/google";
import "./globals.scss";
import NavBar from "@/components/Nav";
import Footer from "@/components/Footer";

const montserrat = Montserrat({
  weight: ['300', '400', '500', '600', '700', '800'],
  subsets: ['latin'],
  display:'swap',
  fallback: ['Arial', 'sans-serif'],
  variable: '--font-montserrat',
});

const playfairDisplay = Playfair_Display({
  subsets: ['latin'],
  variable: '--font-playfairDisplay',
});

export const metadata = {
  title: "Immorose",
  description: "Generated by Immorose",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${playfairDisplay.variable}`}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
